# SHELL / SYSTEM
shell                       /home/alex/.nix-profile/bin/zsh
linux_display_server        wayland
confirm_os_window_close     0
update_check_interval       0
shell_integration           enabled no-cursor


# PERFORMANCE
sync_to_monitor             yes
repaint_delay               6
input_delay                 1
resize_in_steps             yes


# FONT
font_family                 JetBrainsMono Nerd Font
font_size                   11.6
disable_ligatures           never


# CURSOR
cursor_shape                beam
cursor_blink_interval       0
cursor                      #d3af86
cursor_text_color           #221a0f


# MOUSE
copy_on_select              yes
strip_trailing_spaces       always


# WINDOW
window_title_format         {cwd}
window_border_width         1px
window_padding_width        6
window_margin_width         8

background_opacity          0.93
background_blur             48


# TAB BAR
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         angled
tab_bar_min_tabs            1
tab_bar_align               left

# TAB COLORS
# active_tab_background       #FF6188
# active_tab_foreground       #1E1E1E
# inactive_tab_background     #3E3D32
# inactive_tab_foreground     #C5C8C6


# WINDOW BORDER COLORS
# active_border_color         #FF6188
# inactive_border_color       #3E3D32


# BASE COLORS
# background                  #1E1E1E
# foreground                  #C5C8C6

# selection_background        #575B61
# selection_foreground        #FFFFFF

# url_color                   #78DCE8

# Black
# color0                      #1E1E1E
# color8                      #6E7066

# Red
# color1                      #FF6188
# color9                      #FF7EA8

# Green
# color2                      #A9DC76
# color10                     #B8E986

# Yellow
# color3                      #FFD866
# color11                     #FFE37E

# Blue
# color4                      #78DCE8
# color12                     #8BE9FD

# Magenta
# color5                      #AB9DF2
# color13                     #C4B5FD

# Cyan
# color6                      #78DCE8
# color14                     #8BE9FD

# White
# color7                      #C5C8C6
# color15                     #F8F8F2


# FONT SIZE SHORTCUTS
map ctrl+shift+> increase_font_size
map ctrl+shift+< decrease_font_size
map ctrl+shift+0 reset_font_size


# CLIPBOARD
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard


# TABS
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab

map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9


# WINDOWS
map ctrl+shift+enter new_window
map ctrl+left_button move_window
